# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f70145998d17be7f58a78444841b57f3fbb2e9dc65724a666574640312ab74d22b2a1629be0a612e5ae8324173a4b572121dd78e37289930b42f2d2d6e44f67b

test:
  secret_key_base: f35875ae38a05c4f8cace86eabf1e86e4d0015802fc3512269618672f969f2942fe5b33b79c88e0cc65d8df205b29bc93f157837661c9b24fd497c1432633680

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
